id: PF1B3DD1B
initial_creation_type: ocr
source_metadata:
  volumes:
    2ecbbec5b1d44b10af63e1656a6d9aa1:
      base_file: v049.txt
      image_group_id: I1PD95894
      title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་སྟོང་ཕྲག་ཉི་ཤུ་ལྔ་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་ཚིག་ལེའུར་བྱས་པའི་རྣམ་པར་འགྲེལ་པ།
      total_pages: 1182
      volume_number: 49
